---
- hosts: all
  connection: ssh
  tasks: 
  - name: Configure haproxy
    blockinfile:
      path: /etc/haproxy/haproxy.cfg
      state: present
      insertafter: EOF
      block: |
             server iis1 192.168.2.144:80 check
             server iis2 192.168.2.145:80 check

  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
