---
- hosts: localhost
  tasks:

  - name: Authenticate to RHV-M
    ovirt_auth:
      url: "https://{{ rhvm_addr }}/ovirt-engine/api"
      username: "{{ rhv_user }}"
      password: "{{ rhv_pass }}"
      insecure: true

  - name: List vms
    ovirt_vm_facts:
      auth: "{{ ovirt_auth }}"
      pattern: name=iis*

  - name: Get VM API info
    uri:
      url: "https://{{ rhvm_addr }}{{ item.href }}/reporteddevices"
      method: GET
      return_content: yes
      user: "{{ rhv_user }}"
      password: "{{ rhv_pass }}"
      validate_certs: no
      body_format: raw
      headers:
        Accept: application/json
    with_items: "{{ ovirt_vms }}"
    register: vmapi

  - name: Configure haproxy
    blockinfile:
      path: /etc/haproxy/haproxy.cfg
      state: present
      insertafter: EOF
      block: |
             server iis1 "{{ vmapi.results[0].json.reported_device[0].ips.ip[0].address }}":80 check
             server iis2 "{{ vmapi.results[1].json.reported_device[0].ips.ip[0].address }}":80 check
    delegate_to: 192.168.2.147

  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
    delegate_to: 192.168.2.147
