---
- hosts: localhost
  connection: local
  vars: 
    vm_name: "{{ iisvm1 }}"
  gather_facts: no
  roles:
    - {role: 'rhvwindows'}

- hosts: localhost
  connection: local
  vars: 
    vm_name: "{{ iisvm2 }}"
  gather_facts: no
  roles:
    - {role: 'rhvwindows'}
