---
- hosts: all
  tasks:
  - name: Create, update or remove DNS record from AD Zone
    win_dns_record:
      name: "{{ name }}"
      type: "{{ type }}"
      value: "{{ value }}"
      state: "{{ state }}"
      zone: "{{ zone }}" 
