---
- hosts: all
  tasks:
  - name: Remove static record
    win_dns_record:
      name: "{{ name }}"
      type: "{{ type }}"
      value: "{{ value }}"
      state: "{{ state }}"
      zone: "{{ zone }}" 
