---
    - name: Install IIS Web-Server with sub features and management tools
      win_feature:
        name: Web-Server
        state: present
        restart: True
        include_sub_features: True
        include_management_tools: True

    - name: Pause for module refresh
      pause:
        seconds: 5

    - name: Import IIS Module
      win_shell: Import-Module WebAdministration

    - name: Create index.html file in default site
      win_lineinfile:
        create: yes
        path: C:\inetpub\wwwroot\index.html
        line: "You are currently on {{ ansible_ip_addresses[0] }}"

    - name: Create Windows Firewall rule to allow HTTP traffic on port 80
      action: win_firewall_rule
      args:
        name: http
        enable: yes
        state: present
        localport: 80
        action: allow
        direction: In
        protocol: TCP
