---
# tasks file for rhvwindows
 - name: Authenticate to RHV-M
   ovirt_auth:
     url: "https://{{ rhvm_addr }}/ovirt-engine/api"
     username: "{{ rhv_user }}"
     password: "{{ rhv_pass }}" 
     insecure: true

 - name: create the VM
   ovirt_vms: 
     auth: "{{ ovirt_auth }}"
     state: running
     name: "{{ vm_name }}"
     cluster: "{{ cluster }}"
     wait: True
     template: "{{ template_name }}"
     sysprep:
         host_name: "{{ vm_name }}"
         user_name: ansible
         root_password: "{{ admin_pw }}"
         timezone: 'US Eastern Standard Time'

 - name: Wait for Windows build & reboots
   pause:
     seconds: 60

 - name: List vms
   ovirt_vms_facts:
     auth: "{{ ovirt_auth }}"
     pattern: name="{{ vm_name }}"

 - name: Get VM API info
   uri:
     url: "https://{{ rhvm_addr }}{{ item.href }}/reporteddevices"
     method: GET
     return_content: yes
     user: "{{ rhv_user }}"
     password: "{{ rhv_pass }}"
     validate_certs: no
     body_format: raw
     headers:
       Accept: application/json
   with_items: "{{ ovirt_vms }}"
   register: vmapi

 - name: add  server to inventory
   add_host:
     hostname: "{{ item.json.reported_device[0].ips.ip[0].address }}"
     ansible_ssh_user: Administrator
     ansible_ssh_pass: "{{ admin_pw }}"
     ansible_port: 5985 
     ansible_connection: winrm
     groupname: winclients
   with_items: "{{ vmapi.results }}"

 - name: Tag VM as 'provsioning'
   ovirt_tags:
     auth: "{{ ovirt_auth }}"
     name: provisioning
     state: attached
     vms: 
       - "{{ vm_name }}"

# - name: Wait for Windows build & reboots
#   pause: 
#     seconds: 300
